### ISSUE TITLE
Metashell core dumps when leaving mdb

### ISSUE THREAD

**Issue by sabel83** [metashell/metashell#109]
When a valid included file changes to an invalid one while mdb is running, Metashell core dumps when the user is leaving mdb

Reproduction:
1. Create an empty `test.hpp` file
2. Start Metashell, run `#include "test.hpp"`
3. Run `#msh mdb int`
4. Change the content of `test.hpp` to `foo`
5. Press `Ctrl-D` in mdb
6. Metashell crashes (uncaught exception)

**Comment by r0mai** [comment]
The problem is that pch generation [throws an exception](https://github.com/metashell/metashell/blob/03a6d13/lib/core/engine_clang.cpp#L731), and there is no sensible place to catch the exception.

Pch generation is triggered by [setting the pch mode](https://github.com/metashell/metashell/blob/03a6d132791db6f11c7506e021d59fdf210218e1/lib/core/shell.cpp#L450) on `shell`, which is set by `mdb_shell`'s destructor through a [disable_precompiled_header_guard](https://github.com/metashell/metashell/blob/03a6d13/lib/core/disable_precompiled_header_guard.cpp#L35).

**Comment by r0mai** [comment]
The exception should be caught by something in `shell`, which has access to a `displayer`.
Unfortunately there is no such frame in the stack at the point of throw:

```
frame #0 : libc++abi.dylib`__cxa_throw
frame #1 : (anonymous namespace)::engine_clang<true>::generate_precompiled_header at engine_clang.cpp:736
frame #2 : metashell::header_file_environment::save at header_file_environment.cpp:226
frame #3 : metashell::header_file_environment::append at header_file_environment.cpp:192
frame #5 : metashell::shell::rebuild_environment at shell.cpp:469
frame #6 : metashell::shell::using_precompiled_headers at shell.cpp:450
frame #7 : metashell::disable_precompiled_header_guard::~disable_precompiled_header_guard at disable_precompiled_header_guard.cpp:36
frame #10: metashell::mdb_shell::~mdb_shell
frame #17: metashell::command_processor_queue::pop
frame #28: metashell::input_loop at input_loop.cpp:67
frame #29: main at main.cpp:139
```

The solution should probably be, that `mdb_shell` shouldn't set the pch mode in `shell` at all, since no new input can be entered to the environment in an mdb session.

**Comment by sabel83** [comment]
The reason why `mdb_shell` sets pch mode is that pch generation is normally enabled in the shell to make it work faster but Templight fails to generate usable dumps when pch generation is enabled, so `mdb_shell` disables it for the mdb session. I'm not sure if we can change that.

`command_processor_queue::pop` could catch the exceptions thrown by the command processor destructors and display the error (and move on). Or if we want to avoid throwing destructors, then we can introduce a `tear_down(displayer& displayer_)` method in `iface::command_processor` which is called before the object is destructed so the potentially throwing operations can be done there.
