### ISSUE TITLE
Clang integration status

### ISSUE THREAD

**Issue by thomaslepoix** [metashell/metashell#259]
Hey! :)

I found this thread https://reviews.llvm.org/D5767 and indeed the `-cc1` command line of modern clang versions has the `-templight-dump` argument. So I am wondering why you still ship a custom version of clang with metashell instead of relying of the upstream versions.

Also trying to use `clang -cc1 -templight-dump` with [Templar](https://github.com/schulmar/Templar), it seemed to me that the produced output format was different from the templight output (I precise I never tried the [mikael-s-persson's templight](https://github.com/mikael-s-persson/templight) nor the fork you maintain in the metashell repo so I didn't investigate more than that).

Could you explain the current situation about that?

**Comment by sabel83** [comment]
This repo doesn't fork mikael-s-persson's templight, the code is just copied into this repository (and kept up to date). Metashell is still using that because:

- the `-templight-dump` output doesn't support benchmarking the template instantiation speed
- the `templight` binary and its protobuf format is faster which is important for larger metaprograms

Note that Metashell works with both the custom build and the upstream versions. If you'd like Metashell to use an upstream (or other) clang with `-templight-dump`, then you need to start it with `metashell -- <path to the clang binary> <any further command line option to pass to clang>`

**Comment by thomaslepoix** [comment]
Ok I understand, thank you!

Couldn't the `-ftime-trace` flag (used by [ClangBuildAnalyzer](https://github.com/aras-p/ClangBuildAnalyzer)) be combined with `-templight-dump` to support instantiation speed? It won't solve the text vs. protobuf matter though.

**Comment by thomaslepoix** [comment]
I close as you answered my question but feel free to continue the discussion. :)
